### ISSUE TITLE
How compile last solution?

### ISSUE THREAD

**Issue by dguarneri71** [estruyf/react-handlebars-search#14]
Hi estruyf, I can't compile the project.
My environment is
node.js: **v6.11.5**
microsoft/generator-sharepoint: **microsoft/generator-sharepoint@1.3.4**
generator-sharepoint is globally installed.

How can compile this project? I'm new in spfx, is possible install generator-sharepoint locally for this solution?

thank you so much

![image](https://user-images.githubusercontent.com/36726531/36527720-1857d984-17b3-11e8-9dc9-97ff6d020745.png)

**Comment by estruyf** [comment]
What do you get when you try to run `gulp bundle`?

**Comment by dguarneri71** [comment]
Hi,
when I run "npm install"
![image](https://user-images.githubusercontent.com/36726531/36535896-6edcf95c-17cb-11e8-8d5d-6ada0531d9d0.png)

and when I run "gulp bundle"
![image](https://user-images.githubusercontent.com/36726531/36536125-220d2ba0-17cc-11e8-853f-a48ef2cc29d5.png)

**Comment by estruyf** [comment]
The ones from `npm` you can ignore, the `gulp bundle` one is a problem which is already fixed in the dev branch. I will do a merge right now.

**Comment by estruyf** [comment]
I merged with the dev branch, so this should be working again. Clone this repo again and you can start.

**Comment by dguarneri71** [comment]
thanks

**Comment by dguarneri71** [comment]
It works now, thank you

**Comment by estruyf** [comment]
np
