### ISSUE TITLE
itemAt not available

### ISSUE THREAD

**Issue by bartvermeersch** [estruyf/react-handlebars-search#18]
Hi @estruyf , thank you for this amazing webpart! One question, "itemAt" is not available in the handlebars-helpers version 0.8.2. Is there a reason not to use a more recent version of handlebars-helpers?

**Comment by estruyf** [comment]
It uses the version of the `handlebars-helpers` when it was added to the web part. For sure this version can be upgraded to the latest. I'll put it in the next release.

**Comment by estruyf** [comment]
Lates DEV version is using this version.

**Comment by estruyf** [comment]
The latest master has v0.8.4 available. Later versions of `handlebars-helpers` are not yet supported due to a dependency written in ES6.
