### ISSUE TITLE
Sorting error message when using a non-sortable managed property

### ISSUE THREAD

**Issue by bartvermeersch** [estruyf/react-handlebars-search#22]
When specifying a managed property to sort the search results, an error appears in the webpart when the managed property is non-sortable:

"Invalid parameter: SortList."

A more accurate error message or indication on the UI about this requirement (Make sure the property is sortable) could be very useful for users unaware of this limitation!

**Comment by estruyf** [comment]
Doing some updates to the web part, and implemented the `PropertyFieldCollectionData` control from `@spfx/spfx-property-controls`. This allows you to do the following validation + it's also easier to add the MPs:

![screenshot 2018-09-21 12 36 45](https://user-images.githubusercontent.com/2900833/45876770-eab34d80-bd9b-11e8-9b18-ccc75eff3661.png)

**Comment by estruyf** [comment]
This control is now available in the latest master version.
