### ISSUE TITLE
Performance issue in Firefox (and Safari?)

### ISSUE THREAD

**Issue by bartvermeersch** [estruyf/react-handlebars-search#23]
We encouter strange performance issues with the webpart. The call to https://abc.sharepoint.com/sites/abc/_api/search/query?QueryText='.... 

takes 20.000 ms in Firefix and only 200 ms in Edge and Chrome.

The headers spclientservicerequestduration and sprequestduration are also very high in Firefox (25.000) compared to Edge/Chrome (<200).

When going directly to https://abc.sharepoint.com/sites/abc/_api/search/query?QueryText='....  all browsers respond quickly. 

Is our assumption correct that firefox must be sending slightly different requestheaders and SPO is a bit freaked out by it?

**Comment by estruyf** [comment]
That's indeed weird. I'm doing some updates to the WP at the moment and also using FF for debugging and don't see any differences on my side.

![screenshot 2018-09-21 12 40 03](https://user-images.githubusercontent.com/2900833/45876680-9a3bf000-bd9b-11e8-9460-62e8e87a459a.png)

This is already using the latest version based on v1.6.0, but normally that shouldn't make a difference to the fetch.

**Comment by VosjeGamingPolyglot** [comment]
I also fear the same problem is occuring in Safari. I also noticed that with some users (in Safari) they sometimes get an error and the web part won't load. If they switch to chrome on Mac they never get this problem. I don't know if this problem is fully or partially related. But it is worth mentioning.

**Comment by bartvermeersch** [comment]
@VosjeGamingPolyglot can you check if you can reproduce this in FF? 

@estruyf maybe it is tenant related (with all the new features coming out). On a brand new page, without any customization to the webpart, it can take 55s to load the webpart in FF...

![afbeelding](https://user-images.githubusercontent.com/1407940/45879144-ac219100-bda3-11e8-9502-1d7b2ba6db90.png)

We tried changing the request headers to match them with the headers used by Edge/Chrome without success.

**Comment by estruyf** [comment]
@bartvermeersch can you check the `x-sharepointhealthscore` number of your tenant? This is a header property on the page calls from SharePoint.

**Comment by bartvermeersch** [comment]
It's 2 (in all browsers) which is ok I guess.

**Comment by estruyf** [comment]
Yes, I have `4` 🙂, lower is better.

**Comment by estruyf** [comment]
Would you be able to test out the version from the DEV branch? Just to see if v1.6.0 solves anything?

**Comment by VosjeGamingPolyglot** [comment]
That's a good idea. We have to be carefull not to impact production though. @bartvermeersch can you do this on a dev tenant?

**Comment by estruyf** [comment]
You can run a DEV build locally, which doesn't impact the production environment and test it out on the workbench: `https://tenant.sharepoint.com/_layouts/15/workbench.aspx`

**Comment by VosjeGamingPolyglot** [comment]
Yes that's true. Didn't think of it before. That's safer, don't know if it will give the same results though. It should...

**Comment by VosjeGamingPolyglot** [comment]
One little snag though, perhaps a silly question. But if the handlebars web part is already deployed in a tenant. Than this web part is off course also available in the select menu of the online workbench. So how can you select the local version of a web part (running from the dev branch). :)

**Comment by estruyf** [comment]
On the workbench, it checks the one coming from the localhost.

**Comment by VosjeGamingPolyglot** [comment]
Oh, so I was worrying about nothing then :)

**Comment by estruyf** [comment]
Better safe than sorry

**Comment by bartvermeersch** [comment]
The issue is also present on the modern search page which uses a similar API call. Premier support is looking into it. Thank you @estruyf

**Comment by estruyf** [comment]
Cool, if you know more, could you give me an update? Interested to know more about it 🙂
