### ISSUE TITLE
Create a local version of the Office UI Fabric css

### ISSUE THREAD

**Issue by estruyf** [estruyf/react-handlebars-search#7]
Create a local version of the Office UI Fabric CSS that can be used in the handlebar templates

**Comment by ytterstrom** [comment]
A Office UI Fabric CSS would be a wonderful addition! I really like the approch to separate the design to a external template, instead of building fabric react components in the source code. This leads to me using the same webpart with different designs in the site, which is neat!

**Comment by estruyf** [comment]
This is now implemented. The web part loads a scoped UI Fabric version (v6). So you would be able to use all the UI Fabric styles.
