### ISSUE TITLE
Next and Previous buttons interfere between web parts

### ISSUE THREAD

**Issue by kmosti** [estruyf/react-handlebars-search#8]
To reproduce:

Add two search web parts to one page, with paging enabled.

Sometimes, one set of buttons will work, sometimes not. Sometimes selecting next will select next for both pages, sometimes not.

[quick demonstration of the issue](https://gfycat.com/ifr/WavyFamiliarAfricanclawedfrog "demo")

**Comment by estruyf** [comment]
That is a great catch. It is indeed a bug because both will have the same class defined. I have updated the code to add a unique ID per web part. If you redownload the code and to an `npm install` now work for both web parts.

**Comment by kmosti** [comment]
Yes, thank you that works!
