### ISSUE TITLE
How to add rendering logic in the handlebar templates?

### ISSUE THREAD

**Issue by kmosti** [estruyf/react-handlebars-search#9]
This might be a stupid question, but I cannot find a way to achieve what I intend using only handlebars (and I admit I am very new to handlebars).

Say you want the search result to include a file icon, so you find the corresponding icons like ms-Icon--OpenFile and similar.

Next you pull the FileExtension prop from the search results, but then you need to do some logic comparison to say "If doc or docx, show the msWord icon".

Handlebars does not seem a good match here (because it only does templating and doesn't seem to have any helpers for this purpose), but is there some way to modify the web part, like adding another handlebar helper for logic comparison or adding some way to do JS pre-processing of the returned items object, so that I could achieve this?

**Comment by estruyf** [comment]
That is totally possible to achieve in the Handlebar template. The web part automatically includes a large library of Handlebars helpers: https://github.com/helpers/handlebars-helpers.

In that library, you will find a lot of helpers that can be used for various types of content (string, array, objects). One of them is the `eq` helper. This one can be used to check if a value is equal to another value. In your case, you could use this to check if the `FileExtension` managed property is equal to `doc` or `docx` for example.

Here is a code example of what you could add to your template:
```javascript
{{#eq FileExtension "aspx"}}
  webpage
{{/eq}}
{{#eq FileExtension "pdf"}}
  Adobe PDF
{{/eq}}
```

**Comment by kmosti** [comment]
Hah, as I mentioned I've never used Handlebars, so thanks for answering my simple question.

After having played around with the solution I can say that I really admire your work, thank you for both that and your help so far :-)
